### ISSUE TITLE
Using pathschanged with jsonnet

### ISSUE THREAD

**Issue by leandroandrade87** [meltwater/drone-convert-pathschanged#33]
Hi, i would like to know if there's some limitation to use pathschangeg with jsonnet?

I'm trying to use, but every time that i commit something, all steps runs.

I already generate the yml file using `drone jsonnet --target .drone-json.yml --stream ` and if i use this yml file, the pathschange works fine, but if i change to use jsonnet don't.

YML file generated:
```
---
kind: pipeline
name: terraform-buildstaging-plan

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

steps:
- name: terraform-acm-plan
  pull: always
  image: my-pipeline
  settings:
    command: plan
    folders: acm
  environment:
    AWS_DEFAULT_REGION: us-east-1
  when:
    branch:
      exclude:
      - master
    event:
      exclude:
      - pull_request
    paths:
      include:
      - terraform/acm/**
      exclude:
      - README.md
  depends_on:
  - clone
...
```

PS.: I put the exclude just to test. If i use only include, the yml generated exclude the *include* key.
