### ISSUE TITLE
Use the clauses in triggers

### ISSUE THREAD

**Issue by cbisio** [meltwater/drone-convert-pathschanged#39]
Hi!
Have you considered the possibility of using this include/exclude clauses for the trigger phase?
Example:
```
trigger:
  event:
  - push
  paths:
    exclude:
    - some-path/**"
```
