### ISSUE TITLE
Error: cannot unmarshal !!map into string

### ISSUE THREAD

**Issue by hwittenborn** [meltwater/drone-convert-pathschanged#54]
I've been hacking at this for the last few hours, but nothing's seeming to fix it.

Here's the full YAML file if it helps:
```
---
name: Build and Publish (Alpha Release)
kind: pipeline
type: docker
environment:
  test: testing
  pkgname: mpm\-alpha
  release_type: alpha
  nexus_repository_password:
    from_secret: nexus_repository_password
  DEBIAN_FRONTEND: noninteractive

trigger:
  event:
    - push
  branch:
    - alpha
  paths:
    include:
      - src/PKGBUILD
      - .trigger

steps:
  - name: build
    image: ubuntu
    commands:
      - scripts/build.sh
---
kind: signature
hmac: 0bd067baf86af239a29ff6d44954f8e4abeba37c9be15a7952245799d21b7c88

...
```
