### ISSUE TITLE
Feature request: Trigger paths logic by conditions

### ISSUE THREAD

**Issue by digitalnomd** [meltwater/drone-convert-pathschanged#56]
Trigger only on feature branches or if a certain keyword is contained within the commit message similar to how "[skip ci]" works. The rest of the time ignore the when-paths logic.

**Comment by hikerspath** [comment]
This should already be possible with the following triggering:

```yaml
trigger:
  ref:
    include:
      - refs/heads/feature-*
  paths:
    include:
      - /paths/to/include/**
```

or on an individual step as follows

```yaml
step:
  - name: something
    image: something-else:1.0.0
    when:
      ref:
        include:
          - refs/heads/feature-*
      paths:
        include:
          - /paths/to/include/**
```

See [Triggering](https://docs.drone.io/pipeline/triggers) in drone docs...
