### ISSUE TITLE
Feature: Support both `event` and `paths` under `trigger` block

### ISSUE THREAD

**Issue by dsotirakis** [meltwater/drone-convert-pathschanged#70]
Currently, I am trying to setup a pipeline that runs on `pull_requests` but exclude some changes. My `.drone.yml` looks like this:

```
kind: pipeline
name: pr

trigger:
  event:
  - pull_request
  paths:
    exclude:
    - README.md
 ...
```

It seems to pickup the `event` trigger, and ignore the `paths` block. Is it desirable? I wonder if it's possible to declare `exclude` without having an `include` declaration?

On the same yaml file, I also have:

```
---
kind: pipeline
name: test-pr

trigger:
  paths:
    - README.md
 ...
```
so effectively what happens, is when I make `README.md` changes, two jobs are triggered once I push to Github: On the first job, both `pr` and `test-pr` pipelines run, while on the second job, only `test-pr` pipeline runs.

Ideally, what I'd like is to run everything for the `pr` pipeline, only when there are not `README.md` changes, without running `test-pr` in parallel, and run `test-pr` pipeline when there are changes on `README.md` file, but for `pull_requests` only.

**Comment by talelk** [comment]
+1

**Comment by jimsheldon** [comment]
Thanks for submitting this, I am investigating.

**Comment by jimsheldon** [comment]
So I ran some tests where I focused on the last line of your post:

> Ideally, what I'd like is to run everything for the `pr` pipeline, only when there are not `README.md` changes, without running `test-pr` in parallel, and run `test-pr` pipeline when there are changes on `README.md` file, but for `pull_requests` only.

Here is the .drone.yml I used, which I think matches your example, with the exception that I added the `pull_request` trigger since you specifically say you only want the `test-pr` pipeline to run when `README.md` changes in a pull request.

```yaml
kind: pipeline
name: pr

trigger:
  event:
  - pull_request
  # paths rule with explicit exclude on README.md
  paths:
    exclude:
    - README.md

steps:
- name: echo
  image: busybox
  commands:
  - echo "this is a pull request where README.md was not changed"

---
kind: pipeline
name: test-pr

trigger:
  event:
  - pull_request
  # paths rule with implicit include on README.md
  paths:
  - README.md

steps:
- name: echo
  image: busybox
  commands:
  - echo "this is a pull request where README.md was changed"
```

With this .drone.yml, when I opened a pull request where only `README.md` was changed, only the `test-pr` pipeline ran. If I opened a pull request with a file other than `README.md` changed, only the `pr` pipeline ran. This seems to be the behavior you are looking for, so I'm afraid I don't see the same issue you are seeing.

This was tested with drone server 2.4.0, and version 0.5.0 of the paths plugin.

Please let me know if I am misunderstanding your issue.
