### ISSUE TITLE
trouble get it running - converter: cannot convert configuration

### ISSUE THREAD

**Issue by jboesh** [meltwater/drone-convert-pathschanged#80]
I'm trying to get it to work on my existing Gitea and DroneCI.
Your image appears to be running but fails in DroneCI and gets the following error

```
{"level":"info","msg":"server listening on address :3000","time":"2021-12-19T16:11:06Z"}
{"build_action":"","build_after":"d8aa21222644e2d4c3da049a63a68ccff7e264cc","build_before":"7f8d4ce2eb5cd416be621e83af3dc5869516be65","build_event":"push","build_ref":"refs/heads/master","build_source":"master","build_target":"master","build_trigger":"@hook","level":"info","msg":"initiated","repo_name":"blog","repo_namespace":"gitea","time":"2021-12-19T16:33:29Z"}
{"build_after":"d8aa21222644e2d4c3da049a63a68ccff7e264cc","build_before":"7f8d4ce2eb5cd416be621e83af3dc5869516be65","level":"info","msg":"a path field was seen","repo_name":"blog","repo_namespace":"gitea","time":"2021-12-19T16:33:29Z"}
{"level":"debug","msg":"converter: cannot convert configuration: gitea/blog: master: ","time":"2021-12-19T16:33:29Z"}
```

How my docker compose looks like:
```
version: "3"
services:
  gitea:
    image: gitea/gitea:1.14.6
    volumes:
      - /share/docker/swarm/appdata/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  drone:
    image: drone/drone:2.1.0
    environment:
      - DRONE_DEBUG=true
      - DRONE_ADMIN=admin
      - DRONE_USER_CREATE=username:admin,admin:true
      - DRONE_SERVER_PORT=:80
      - DRONE_DATABASE_DRIVER=sqlite3
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_GITEA_SERVER=https://gitea.mydomain.com
      - DRONE_RPC_SECRET=ert26a2221fd8090ea38720fc445eca6
      - DRONE_SERVER_HOST=drone.mydomain.com
      - DRONE_HOST=https://drone.mydomain.com
      - DRONE_SERVER_PROTO=https
      - DRONE_TLS_AUTOCERT=false
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GITEA_CLIENT_ID=06854c15-3165-4627-4352-8c5e25d7249d
      - DRONE_GITEA_CLIENT_SECRET=r4lJu-xetRS1WQA0DFGBkT_uwayKaNmNZ6L0dYsbEi0=
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_TEXT=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true
      - DRONE_CONVERT_PLUGIN_ENDPOINT=http://192.168.1.174:3003
      - DRONE_CONVERT_PLUGIN_SECRET=ert26a2221fd8090ea38720fc445eca6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /share/docker/swarm/appdata/drone:/data

  drone-convert-pathschanged:
    image: meltwater/drone-convert-pathschanged
    depends_on:
      - drone
    environment:
      - DRONE_DEBUG=true
      - DRONE_SECRET=ert26a2221fd8090ea38720fc445eca6
      - TOKEN=44b979dc674998f99906865de89f6896abb67197
      - PROVIDER=github
      - GITHUB_SERVER=https://gitea.mydomain.com
    ports:
      - 3003:3000
```

Am I missing somsthing here?
should DRONE_CONVERT_PLUGIN_ENDPOINT be the url of the convert image?
and DRONE_CONVERT_PLUGIN_SECRET the same as DRONE_RPC_SECRET?

thanks in advance.
