### ISSUE TITLE
invalid signature in http.Request

### ISSUE THREAD

**Issue by 3sky** [meltwater/drone-convert-pathschanged#86]
### Describe the bug

I have an issue with the configuration converter + drone server. I'm using docker-compose on linux/amd64.
I'm almost sure that config has a problem with handling: `DRONE_CONVERT_PLUGIN_ENDPOINT` which isn't an IP. 
When I'm trying to use `DRONE_CONVERT_PLUGIN_ENDPOINT=drone_converter:3000` logs produced:

```bash
drone            | {"commit":"8583cff5096fde2cba19cdf929cda668d11929ca","error":"parse \"drone_converter:3000\": first path segment in URL cannot contain colon","event":"push","level":"warning","msg":"trigger: cannot convert yaml","ref":"refs/heads/kuba/droneCI","repo":"3sky/solid","time":"2022-03-24T14:52:59Z"}
```
Important that pipeline code looks like that:

```bash
trigger:
  event:
    - push
  paths:
    include:
      - .golangci.yml

steps:
- name: run linter
  image: golangci/golangci-lint:v1.45-alpine
  commands:
    - golangci-lint run
```

When I'm using `DRONE_CONVERT_PLUGIN_ENDPOINT=http://drone_converter:3000`
```bash
drone_converter  | {"level":"info","msg":"server listening on address :3000","time":"2022-03-24T14:58:11Z"}
drone_converter  | {"level":"debug","msg":"converter: invalid signature in http.Request","time":"2022-03-24T14:58:47Z"}
```
### Steps to reproduce

My docker-compose looks like that:

```yaml
version: '3.6'
networks:
  drone_net:
    external: true

volumes:
  drone_data:

services:
  drone:
    image: drone/drone:${DRONE_VERSION}
    container_name: drone
    restart: always
    hostname: drone
    volumes:
     - drone_data:/data
    environment:
      - TZ=UTC
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SECRET=${DRONE_CONVERTER_SECRET}
      - DRONE_DATABASE_SECRET=${DRONE_DATABASE_SECRET}
      - DRONE_CONVERT_PLUGIN_ENDPOINT=http://drone_converter:3000
      - DRONE_SERVER_HOST=drone.3sky.dev
      - DRONE_SERVER_PROTO=http
      - DRONE_USER_FILTER=3sky
      - DRONE_USER_CREATE=username:3sky,admin:true
    networks:
      drone_net:

  drone-converter:
    container_name: drone_converter
    image: meltwater/drone-convert-pathschanged:${DRONE_CONVERTER_VERSION}
    depends_on: [ drone ]
    restart: always
    environment:
     - TZ=UTC
     - DRONE_DEBUG=true
     - DRONE_RPC_HOST=drone
     - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
     - TOKEN=${DRONE_GITHUB_CLIENT_SECRET}
     - DRONE_SECRET=${DRONE_CONVERTER_SECRET}
     - PROVIDER=github
    networks:
      - drone_net
```

```bash
docker-compose up
```

And the logs:

```bash
drone            | {"acme":false,"host":"drone.3sky.dev","level":"info","msg":"starting the http server","port":":80","proto":"http","time":"2022-03-24T14:58:10Z","url":"http://drone.3sky.dev"}
drone            | {"interval":"30m0s","level":"info","msg":"starting the cron scheduler","time":"2022-03-24T14:58:10Z"}
drone            | {"interval":"24h0m0s","level":"info","msg":"starting the zombie build reaper","time":"2022-03-24T14:58:10Z"}
drone_converter  | {"level":"info","msg":"server listening on address :3000","time":"2022-03-24T14:58:11Z"}
drone_converter  | {"level":"debug","msg":"converter: invalid signature in http.Request","time":"2022-03-24T14:58:47Z"}
drone            | {"commit":"d6736f08d0cfa7d749406171ba796b2ba79855bb","error":"Invalid Signature\n","event":"custom","level":"warning","msg":"trigger: cannot convert yaml","ref":"refs/heads/kuba/droneCI","repo":"3sky/solid","time":"2022-03-24T14:58:47Z"}

### Expected behavior

I expected a connection with the converter.
